# Generated by Django 4.2 on 2023-05-18 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('register_num', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_number', models.CharField()),
                ('street_name', models.CharField()),
                ('register_number', models.CharField()),
                ('parking_time', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cars_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carsFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cars')),
                ('id_usersFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.users')),
            ],
        ),
        migrations.CreateModel(
            name='Cars_Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carsFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cars')),
                ('id_paymentsFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.payments')),
            ],
        ),
    ]
