# Generated by Django 4.0 on 2023-06-12 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('register_num', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_number', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=100)),
                ('register_number', models.CharField(max_length=100)),
                ('parking_time', models.CharField(max_length=100)),
                ('car', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.cars')),
            ],
        ),
        migrations.CreateModel(
            name='CarsUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carsFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cars')),
                ('id_usersFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='owner',
            field=models.ManyToManyField(through='base.CarsUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
