# Generated by Django 4.2 on 2023-05-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='login',
        ),
    ]
