# Generated by Django 4.0 on 2023-06-13 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.RemoveField(
            model_name='payments',
            name='car',
        ),
        migrations.AddField(
            model_name='payments',
            name='car',
            field=models.ManyToManyField(through='base.CarsPayments', to='base.Cars'),
        ),
        migrations.AddField(
            model_name='carspayments',
            name='id_carsFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cars'),
        ),
        migrations.AddField(
            model_name='carspayments',
            name='id_paymentsFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.payments'),
        ),
    ]
