# Generated by Django 4.0 on 2023-06-13 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_carspayments_alter_cars_image_remove_payments_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='car',
        ),
        migrations.AddField(
            model_name='payments',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.cars'),
        ),
        migrations.DeleteModel(
            name='CarsPayments',
        ),
    ]
