# Generated by Django 4.2 on 2023-05-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_users_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars_Payments',
            new_name='CarsPayments',
        ),
        migrations.RenameModel(
            old_name='Cars_Users',
            new_name='CarsUsers',
        ),
    ]
