# Generated by Django 4.0 on 2023-06-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_payments_car_payments_car_delete_carspayments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
