# Generated by Django 4.0 on 2023-06-13 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_cars_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.cars'),
        ),
    ]
