# Generated by Django 4.0 on 2023-06-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_cars_id_alter_carsusers_id_usersfk_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payments',
            name='parking_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payments',
            name='register_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payments',
            name='street_name',
            field=models.CharField(max_length=100),
        ),
    ]
